from aiogram.dispatcher.filters.state import State, StatesGroup

class TalkShowForm(StatesGroup):
    job = State()
    other_job = State()
    start_scenario = State()
    question_1 = State()
    question_2 = State()
    question_3 = State()
    question_4 = State()
    question_5 = State()
    question_6 = State()
    question_7 = State()
    question_8 = State()
    question_9 = State()
    question_10 = State()
    question_11 = State()
    question_12 = State()
    question_13 = State()
    question_14 = State()
    question_future = State()
    question_advice_to_newcomers = State()
    end = State()
