"""admin table added

Revision ID: 05927834daa0
Revises: 9ebae0accd9e
Create Date: 2024-04-12 21:33:01.992078

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05927834daa0'
down_revision = '9ebae0accd9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=True)
    op.create_table('message_for_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('path_to_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('daily_news', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('daily_news', sa.Column('publication_date', sa.String(), nullable=True))
    op.add_column('daily_news', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('daily_news', 'file')
    op.drop_column('daily_news', 'type')
    op.drop_column('daily_news', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_news', sa.Column('image', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('daily_news', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('daily_news', sa.Column('file', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('daily_news', 'title')
    op.drop_column('daily_news', 'publication_date')
    op.drop_column('daily_news', 'publisher')
    op.drop_table('message_for_users')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
