"""daily_news text

Revision ID: 161bb894d062
Revises: 7a324b47af2b
Create Date: 2023-11-12 20:15:10.901540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161bb894d062'
down_revision = '7a324b47af2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_news', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_news', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
