"""Added hint table

Revision ID: 1e96b095c23b
Revises: c71b956d516b
Create Date: 2023-12-17 01:45:17.618880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e96b095c23b'
down_revision = 'c71b956d516b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_hint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.String(), nullable=True),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('bot_message_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_message_id'], ['message_history.id'], ),
    sa.ForeignKeyConstraint(['tg_id'], ['user.tg_id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['message_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_hint')
    # ### end Alembic commands ###
