"""Daily news

Revision ID: 4566b4ad19fa
Revises: 930721df6aae
Create Date: 2023-12-20 00:05:41.679287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4566b4ad19fa'
down_revision = '930721df6aae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
