"""Daily news upgrade

Revision ID: 502d0b325b66
Revises: 4566b4ad19fa
Create Date: 2023-12-21 21:43:12.461266

"""
import sqlalchemy_file
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502d0b325b66'
down_revision = '4566b4ad19fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_news', sa.Column('image', sqlalchemy_file.types.ImageField(), nullable=True))
    op.add_column('daily_news', sa.Column('file', sqlalchemy_file.types.FileField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_news', 'file')
    op.drop_column('daily_news', 'image')
    # ### end Alembic commands ###
