"""Added settings for user

Revision ID: 5a484554dd0e
Revises: 97d439dcc668
Create Date: 2024-02-23 13:46:29.730854

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = '5a484554dd0e'
down_revision = '97d439dcc668'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.String(), nullable=True),
    sa.Column('summary_on', sa.Boolean(), nullable=True),
    sa.Column('summary_answered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_id'), 'setting', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_id'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
