"""Added newsletter audio

Revision ID: 6df4ad791d58
Revises: e61cebf44dd4
Create Date: 2024-05-04 19:51:16.541750

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = '6df4ad791d58'
down_revision = 'e61cebf44dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_audio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletter.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_audio')
    # ### end Alembic commands ###
