"""Added speaker in User

Revision ID: 7430b9c8da1b
Revises: 161bb894d062
Create Date: 2023-12-01 16:58:09.436103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7430b9c8da1b'
down_revision = '161bb894d062'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('speaker', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'speaker')
    # ### end Alembic commands ###
