"""daily_news

Revision ID: 7a324b47af2b
Revises: 25b0e9871ca3
Create Date: 2023-11-12 20:04:37.456905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a324b47af2b'
down_revision = '25b0e9871ca3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Unicode(), nullable=True),
    sa.Column('instruction', sa.Unicode(), nullable=True),
    sa.Column('type', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_news')
    # ### end Alembic commands ###
