"""Added url in news

Revision ID: 97d439dcc668
Revises: ebfd492c901b
Create Date: 2024-02-14 22:17:38.409416

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = '97d439dcc668'
down_revision = 'ebfd492c901b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_news', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_news', 'url')
    # ### end Alembic commands ###
