"""Added images in news

Revision ID: c33d27b005b2
Revises: ca19cb9abd06
Create Date: 2023-12-21 20:35:56.427568

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = 'c33d27b005b2'
down_revision = 'ca19cb9abd06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_news', sa.Column('image', sqlalchemy_file.types.ImageField(), nullable=True))
    op.add_column('daily_news', sa.Column('file', sqlalchemy_file.types.FileField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_news', 'file')
    op.drop_column('daily_news', 'image')
    # ### end Alembic commands ###
