"""Added translation table

Revision ID: ca19cb9abd06
Revises: e96faf1a08c8
Create Date: 2023-12-21 05:37:42.495734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca19cb9abd06'
down_revision = 'e96faf1a08c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.String(), nullable=True),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('bot_message_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_message_id'], ['message_history.id'], ),
    sa.ForeignKeyConstraint(['tg_id'], ['user.tg_id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['message_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_translation')
    # ### end Alembic commands ###
