"""Added speaker in User 2

Revision ID: d7536514df91
Revises: 7430b9c8da1b
Create Date: 2023-12-01 17:40:39.445209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7536514df91'
down_revision = '7430b9c8da1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
