"""Changed Daily news

Revision ID: d7a287c1a749
Revises: c71b956d516b
Create Date: 2023-12-14 19:37:01.087073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a287c1a749'
down_revision = 'c71b956d516b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_news', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('daily_news', sa.Column('path_to_data', sa.String(), nullable=True))
    op.alter_column('daily_news', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('daily_news', 'instruction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_news', sa.Column('instruction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('daily_news', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('daily_news', 'path_to_data')
    op.drop_column('daily_news', 'topic')
    # ### end Alembic commands ###
