"""Added paraphrase table

Revision ID: e96faf1a08c8
Revises: 8b44c2f62f63
Create Date: 2023-12-20 01:31:44.044975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96faf1a08c8'
down_revision = '8b44c2f62f63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_paraphrase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.String(), nullable=True),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('bot_message_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_message_id'], ['message_history.id'], ),
    sa.ForeignKeyConstraint(['tg_id'], ['user.tg_id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['message_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_paraphrase')
    # ### end Alembic commands ###
