"""Added additional topic for user

Revision ID: ebfd492c901b
Revises: c33d27b005b2
Create Date: 2024-02-05 05:49:11.321499

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision = 'ebfd492c901b'
down_revision = 'c33d27b005b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('additional_topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'additional_topic')
    # ### end Alembic commands ###
